### ISSUE TITLE
Registering an interface

### ISSUE THREAD

**Issue by ryangjchandler** [phper-framework/phper#124]
Is there an undocumented API for registering custom interfaces as part of an extension?

**Comment by jmjoy** [comment]
Not now, I will add it later.

**Comment by jmjoy** [comment]
Please refer to [_06_module/_07_register_interface](https://github.com/phper-framework/phper/blob/43c8896954a8d4ff7a0ab7ed4fafe3c8510941d3/phper-doc/doc/_06_module/_07_register_interface/index.md#register-interface).
