### ISSUE TITLE
How to write 

### ISSUE THREAD

**Issue by shijunti19** [phper-framework/phper#136]
Foo::setValue("nihao")->print();

Can we implement the form of types? It is very useful when writing databases or modules

**Comment by jmjoy** [comment]
Yes, you can.

**Comment by shijunti19** [comment]
@jmjoy 
```
class Counter {
    public static $count = 0;

    public function __construct() {
        self::$count++; // 访问静态变量并增加计数
    }

    public static function getCount() {
        return self::$count; // 访问静态变量并返回计数
    }
}
```
public static $count = 0;
 class.add_property("count", Visibility::Public, "");


How to add static variables
Should we add a method?
 class.add_static_property("count", Visibility::Public, "");


Hope to add examples of improvement

How to access and set static variables

 self::$count++;

**Comment by jmjoy** [comment]
> How to add static variables
> Should we add a method?
> class.add_static_property("count", Visibility::Public, "");

Alright, I will add it later.

**Comment by shijunti19** [comment]
@jmjoy There is also access to static abnormal variables, which currently seems to be inaccessible
