### ISSUE TITLE
Shower Than C Extension 

### ISSUE THREAD

**Issue by arshidkv12** [phper-framework/phper#149]
Hi
I tested with xdebug profile option with grind cache. 
Functions are slower than c. How to speed up?

**Comment by jmjoy** [comment]
What about the data?

**Comment by arshidkv12** [comment]
![cachegrind](https://i.imgur.com/XltH9Q4.png)


**PHP code:**

```php
for ($i=0; $i < 1000; $i++) { 
        say_hello("sdf");
        strpos("sdfsf", "d", 1);
}
```

**Rust:**
```rust
pub fn say_hello(arguments: &mut [ZVal]) -> phper::Result<()> {

    Ok(())
}
```

**Comment by jmjoy** [comment]
Do you build under `release`?

**Comment by arshidkv12** [comment]
Yes

**Comment by jmjoy** [comment]
![image](https://github.com/phper-framework/phper/assets/8677974/ba5cb81e-151e-406d-ba9f-c4a590f54c5c)

**Comment by arshidkv12** [comment]
> ![image](https://private-user-images.githubusercontent.com/8677974/299555197-ba5cb81e-151e-406d-ba9f-c4a590f54c5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNjUzMzgsIm5iZiI6MTcwNjE2NTAzOCwicGF0aCI6Ii84Njc3OTc0LzI5OTU1NTE5Ny1iYTVjYjgxZS0xNTFlLTQwNmQtYmE5Zi1jNGE1OTBmNTRjNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMDY0MzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjI1NmRlZDEyNjU3YjZlNGExMGE3MzA1MWE4NTI1YzcyMjE5YWI4NzQ5OTg5NWYzZjNjNmQ4ZTY3MGE5NmRmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5mbF9Z292mehZNn5QJYTSAagnavJXTxrrpeT72rBKaw)

0.18 > 0.11 

Why does the Rust function take longer than the C complex O(n) function?

How to optimise it?

**Comment by jmjoy** [comment]
PHP is not very friendly to writing extensions in non-C/C++ languages because PHP's source code is heavy and uses macros, while Rust does not support C macros, so some tricks are needed to achieve the desired effect, which can affect performance. However, the purpose of this project is not to improve performance, but simply to use Rust to write PHP extensions, so performance issues are not considered.
