### ISSUE TITLE
Use stable as develop toolchain

### ISSUE THREAD

**Issue by Xuanwo** [phper-framework/phper#154]
Hi, thank you so much for developing this library. I noticed that we are locked to version `1.65` in the rust-toolchain, which complicates the development workflow. 

How about using the `stable` toolchain for development and adding an MSRV check to ensure it builds correctly?

I'm help to help implement this change.

**Comment by jmjoy** [comment]
This looks great, thanks.

**Comment by Xuanwo** [comment]
> But for development purposes, `rustup override stable` should work.

Use `stable` in `rust-toolchain.toml` can make this process much easier so contributor can join in without extra setup.

**Comment by jmjoy** [comment]
`rust-toolchain` has its reasons for existence, so let's not introduce another solution.

**Comment by Xuanwo** [comment]
Thank you for the explanation. I'm going to close this issue now.
