### ISSUE TITLE
Deprecated PHP 8.0 and earlier versions

### ISSUE THREAD

**Issue by godruoyi** [phper-framework/phper#164]
## Description

Since PHP 8.0 and earlier versions are no longer supported by the official PHP team, is it necessary for us to continue supporting them? I believe removing support for these older versions would simplify and improve our design. Do we have any plans to address this? Thank you.

https://php.watch/versions

**Comment by jmjoy** [comment]
Despite this, PHP7 is still widely used, and it is compatible with PHP8 and PHP7, so there is not much pressure on adaptation. I think PHP7 should continue to be supported.

**Comment by godruoyi** [comment]
thank you @jmjoy, we are on the great way,

**Comment by shijunti19** [comment]
Many old projects are still using PHP 7.3, but they won't upgrade but will continue to use it. So I hope to give a parameter that only requires the most basic functionality to be available, and then maintain it without conflict

For example, we will use National Security 7.3 on PHP 7.3, as long as it can be called and executed normally. PHP cannot execute National Security 7.3, https://crates.io/crates/gmsm
