### ISSUE TITLE
可以多增加点例子吗

### ISSUE THREAD

**Issue by shijunti19** [phper-framework/phper#51]
现在的例子简单加复杂，不太好弄
```rust
use Response;
pub fn make_a031_class() -> StatefulClass<Response> {
    let mut class = StatefulClass::<Response>::new_with_default_state(A031_CLASS_NAME);
}
```
Response.rs(升级后改坏了，不知道怎么写了)
```rust
pub struct Response<T> {
    pub message: String,//这里希望使用&str，直接文字
    pub success: bool,
    pub data: T,
}
impl<T: Send + 'static> Response<T> {
    pub fn success<'a>(&self, message: String, data: T) -> Response<T> {
        Response {
            success: true,
            message: message,
            data,
        }
    }
}
```
我现在不会写这个StatefulClass<Response>的返回，怎么写泛型，以前0.4版本之前是正常，后来升级后不支持了
改版后希望增加点例子教我们怎么写。新版需要'static

我的需求是这样，希望执行后可以返回
{success:true,message:"这是返回信息",data:"这是一个泛型，所有种类的数据"}
或者
{success:false,message:"这是返回信息",data:"这是一个泛型，所有种类的数据"}

**Comment by jmjoy** [comment]
既然`StatefulClass`泛型约束了'static，那你的Response就无法包含非'static的str字段，这是rust的限制也是合理的限制。

**Comment by shijunti19** [comment]
@jmjoy 我不会写，还是希望你们例子里提供个简单的例子供我们参考下。

**Comment by shijunti19** [comment]
@jmjoy You want to provide examples of returning generics
