### ISSUE TITLE
union types

### ISSUE THREAD

**Issue by azjezz** [phper-framework/phper#62]
I think it would be great to add support for union types.

I have the following PHP function:

```php
<?php

declare(strict_types=1);

namespace Psl\Math;

/**
 * @template T of int|float
 *
 * @param T $number
 *
 * @return T
 */
function abs(int|float $number): int|float {
    return $number < 0 ? -$number : $number;
}
```

and currently it's not possible to implement using phper, my suggestion is to add a `Union` enum, so that the following is possible:

```rust
pub fn abs(arguments: &mut [ZVal]) -> phper::Result<Union<f64, i64>> {
    if arguments[0].get_type_info().is_double() {
        Ok(Union::Left(arguments[0].expect_double()?.abs()))
    } else {
        Ok(Union::Right(arguments[0].expect_long()?.abs()))
    }
}
```

ref: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=053e92a7efb0bc82998ddd571b38a2df

**Comment by jmjoy** [comment]
I known what you want, you want the Zval cast to the rust enum like [Scalar](https://docs.rs/phper/0.5.1/phper/types/enum.Scalar.html).

But type declaration (int|float) is not related, this is only a limitation of php syntax.

**Comment by azjezz** [comment]
> this is only a limitation of php syntax.

I don't think so, PHP already supports union types, and the code above is valid ^^"

**Comment by azjezz** [comment]
> I known what you want, you want the Zval cast to the rust enum like [Scalar](https://docs.rs/phper/0.5.1/phper/types/enum.Scalar.html).

Yes, `Scalar` however allows too much, and doesn't allow you to create something like : https://3v4l.org/kh9Tf

where with `Union`, it can be nested ( i.e `Union<int, Union<String, Union<Foo, Bar>>>` = `int|string|Foo|Bar` )

**Comment by jmjoy** [comment]
`Union<int, Union<String, Union<Foo, Bar>>>` is too odd, I think you can write this enum in your code, not `phper`.
