### ISSUE TITLE
偶尔会502

### ISSUE THREAD

**Issue by shijunti19** [phper-framework/phper#93]
自己编写了一个lib
但是刷新会偶尔
502 Bad Gateway
可以实现显示错误吗！
nginx和php都看不到错误
你的框架可以套个全局try吗
我现在用try无法拦截，只能502

**Comment by jmjoy** [comment]
看看fpm-error.log吧。

解决问题而不是什么套全局try。

**Comment by shijunti19** [comment]
@jmjoy [18-Dec-2022 08:15:43] WARNING: [pool www] child 75842 exited on signal 6 (SIGABRT) after 36404.847754 seconds from start
[18-Dec-2022 08:15:43] NOTICE: [pool www] child 105573 started

就是进程退出，看不出什么问题。
我删代码一步步试试看

**Comment by shijunti19** [comment]
@jmjoy 应该我自己对接的https://github.com/messense/jieba-rs有问题，用你们默认的complex没任何问题。

**Comment by jmjoy** [comment]
把coredump打开，用gdb调试下core文件看是哪里导致的。
